# fly.toml app configuration file generated for meumenu on 2023-09-08T12:21:27-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "meumenu"
primary_region = "gru"

[build]

[http_service]
  internal_port = 3333
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
